CREATE TABLE activities (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    occurs_at TIMESTAMP NOT NULL,
    trip_id BIGINT,
    FOREIGN KEY (trip_id) REFERENCES trips(id)
    ON DELETE CASCADE
);